FROM node:20-alpine AS base
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
ARG DATABASE_URL=postgresql://postgres@localhost:5432/postgres
ARG NEXTAUTH_URL=http://localhost:3000
ARG GOOGLE_CLIENT_ID=
ARG GOOGLE_CLIENT_SECRET=
ARG GOOGLE_REDIRECT_URI=
ARG GOOGLE_CALENDAR_REDIRECT_URI=
ARG CALCOM_API_BASE_URL=https://api.cal.com/v2
ARG CALCOM_API_KEY=
ARG CALCOM_BOOKING_API_VERSION=2024-08-13
ARG CALCOM_EVENT_TYPE_ID=
ARG CALCOM_EVENT_TYPE_SLUG=
ARG CALCOM_USERNAME=
ARG CALCOM_WEBHOOK_SECRET=
ARG CALCOM_TIMEZONE=Europe/London
ARG NEXT_PUBLIC_GOOGLE_CLIENT_ID=
ARG APP_EDITION=basic
ARG CHATBOT_ENABLED=false
ARG SHOP_LANGUAGE=en
ARG QDRANT_URL=
ARG QDRANT_COLLECTION=nailbooking-knowledge-v2
ARG CHATBOT_TOP_K=8
ARG CHATBOT_CHUNK_SIZE=512
ARG CHATBOT_CHUNK_OVERLAP=50
ENV DATABASE_URL=$DATABASE_URL
ENV NEXTAUTH_URL=$NEXTAUTH_URL
ENV GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID
ENV GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET
ENV GOOGLE_REDIRECT_URI=$GOOGLE_REDIRECT_URI
ENV GOOGLE_CALENDAR_REDIRECT_URI=$GOOGLE_CALENDAR_REDIRECT_URI
ENV CALCOM_API_BASE_URL=$CALCOM_API_BASE_URL
ENV CALCOM_API_KEY=$CALCOM_API_KEY
ENV CALCOM_BOOKING_API_VERSION=$CALCOM_BOOKING_API_VERSION
ENV CALCOM_EVENT_TYPE_ID=$CALCOM_EVENT_TYPE_ID
ENV CALCOM_EVENT_TYPE_SLUG=$CALCOM_EVENT_TYPE_SLUG
ENV CALCOM_USERNAME=$CALCOM_USERNAME
ENV CALCOM_WEBHOOK_SECRET=$CALCOM_WEBHOOK_SECRET
ENV CALCOM_TIMEZONE=$CALCOM_TIMEZONE
ENV NEXT_PUBLIC_GOOGLE_CLIENT_ID=$NEXT_PUBLIC_GOOGLE_CLIENT_ID
ENV APP_EDITION=$APP_EDITION
ENV CHATBOT_ENABLED=$CHATBOT_ENABLED
ENV SHOP_LANGUAGE=$SHOP_LANGUAGE
ENV QDRANT_URL=$QDRANT_URL
ENV QDRANT_COLLECTION=$QDRANT_COLLECTION
ENV CHATBOT_TOP_K=$CHATBOT_TOP_K
ENV CHATBOT_CHUNK_SIZE=$CHATBOT_CHUNK_SIZE
ENV CHATBOT_CHUNK_OVERLAP=$CHATBOT_CHUNK_OVERLAP
RUN npx prisma generate
RUN npm run build

FROM node:20-alpine
WORKDIR /app
ENV NODE_ENV=production
ENV PORT=3000
ENV HOSTNAME=0.0.0.0
ARG APP_EDITION=basic
ARG CHATBOT_ENABLED=false
ARG SHOP_LANGUAGE=en
ARG QDRANT_URL=
ARG QDRANT_API_KEY=
ARG QDRANT_COLLECTION=nailbooking-knowledge-v2
ARG CHATBOT_TOP_K=8
ARG CHATBOT_CHUNK_SIZE=512
ARG CHATBOT_CHUNK_OVERLAP=50
ARG CHATBOT_EMBEDDING_BASE_URL=
ARG CHATBOT_EMBEDDING_API_KEY=
ARG CHATBOT_EMBEDDING_MODEL=text-embedding-3-small
ENV APP_EDITION=$APP_EDITION
ENV CHATBOT_ENABLED=$CHATBOT_ENABLED
ENV SHOP_LANGUAGE=$SHOP_LANGUAGE
ENV QDRANT_URL=$QDRANT_URL
ENV QDRANT_API_KEY=$QDRANT_API_KEY
ENV QDRANT_COLLECTION=$QDRANT_COLLECTION
ENV CHATBOT_TOP_K=$CHATBOT_TOP_K
ENV CHATBOT_CHUNK_SIZE=$CHATBOT_CHUNK_SIZE
ENV CHATBOT_CHUNK_OVERLAP=$CHATBOT_CHUNK_OVERLAP
ENV CHATBOT_EMBEDDING_BASE_URL=$CHATBOT_EMBEDDING_BASE_URL
ENV CHATBOT_EMBEDDING_API_KEY=$CHATBOT_EMBEDDING_API_KEY
ENV CHATBOT_EMBEDDING_MODEL=$CHATBOT_EMBEDDING_MODEL
COPY --from=base /app/package*.json ./
COPY --from=base /app/node_modules ./node_modules
COPY --from=base /app/.next ./.next
COPY --from=base /app/prisma ./prisma
COPY --from=base /app/src ./src
COPY --from=base /app/tsconfig.json ./
COPY --from=base /app/next.config.ts ./
COPY --from=base /app/prisma.config.ts ./
EXPOSE 3000
CMD ["sh", "-c", "npx tsx prisma/ensure-schema.ts || echo 'WARN: non-destructive schema ensure failed'; npx tsx prisma/seed.ts || echo 'WARN: seed failed; preserving existing data and starting app'; node .next/standalone/server.js"]
