version: '3.8'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/nailbooking?schema=public
      - REDIS_URL=redis://redis:6379
      - NEXTAUTH_SECRET=super-secret-key-change-in-production
      - NEXTAUTH_URL=http://localhost:3000
    depends_on:
      - db
      - redis
    networks:
      - nail-net

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nailbooking
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - nail-net

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - nail-net

volumes:
  pgdata:

networks:
  nail-net:
